version: '3.8'
services:
  hapi-fhir:
    image: hapiproject/hapi:latest
    container_name: hapi_fhir_server
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/hapi
    volumes:
      - ./data:/data


